MVC/Models/Enums.cs
public enum Relation{
            Father,
            Monther,
            Brother,
            Sister,
            None
        }

MVC/Models/ErrorViewModel.cs
namespace mvc_web_app.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC/Models/FamilyModel.cs
namespace WebApplicationGui.Classes
{
    public class FamilyModel
    {
        public int id { get; set; } = 0;

        public string fullName { get; set; } = "";

        public string gender { get; set; } = "";

        public int Age { get; set; } = 0;

        public Relation relation { get; set; } = Relation.None;

        public FamilyModel()
        {
            id = 0;
            fullName = "";
            gender = "";
            Age = 0;
            relation = Relation.None;
        }

        public FamilyModel(int iid, string sfullName, string sgender, int iage, Relation erelation)
        {
            id = iid;
            fullName = sfullName;
            gender = sgender;
            Age = iage;
            relation = erelation;

        }

        public override string ToString()
        {
            return $"ID:{id}, Full Name:{fullName} Gender:{gender}{Environment.NewLine}" +
            $" Age:{Age}{Environment.NewLine} |Relation:{relation}";
        }
    }






}

MVC/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationGui.Classes;

namespace mvc_web_app.Controllers;

public class HelloController : Controller
{
    string msg = "Hello World";

    FamilyModel xx = new FamilyModel();

    public IActionResult index()
    {
        ViewData["Message"] = msg;
        ViewData["Num"] = 10;
        return View();
    }


    public IActionResult searchData(int id = 1)
    {
        var list = new List<FamilyModel>()
        {
            new FamilyModel(1,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(2,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(3,"Aayush Pandit","Male",22,Relation.Father),

        };
        var list2 = new List<FamilyModel>();
        list2.Add(list.Where(p => p.id == id).FirstOrDefault());
        return View(list2);
    }

    public IActionResult GetData()
    {
        // xx=new FamilyModel(1,"Aayush Pandit","Male",22,Relation.Father);
        //ViewData["data"]=xx.ToString();

        int iId = 0;
        string sFullName = HttpContext.Request.Form["txtFullName"].ToString();
        string sGender = HttpContext.Request.Form["txtGender"].ToString();
        int iAge = Convert.ToInt32(HttpContext.Request.Form["numAge"].ToString());
        int iRelation = Convert.ToInt32(HttpContext.Request.Form["txtRelation"].ToString());
        var list = new List<FamilyModel>()
        {
            new FamilyModel(1,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(2,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(3,"Aayush Pandit","Male",22,Relation.Father),

        };
        list.Add(new FamilyModel(iId, sFullName, sGender, iAge, (Relation)iRelation));
        //ViewData["test"]="Testing right now!!!"; //j rakhna ni milcha dict ma, dictionary ho, default chai string linxa
        return View(list);





    }
    public IActionResult AddData()
    {
        // xx=new FamilyModel(1,"Aayush Pandit","Male",22,Relation.Father);
        ViewData["data"] = xx.ToString();

        var list = new List<FamilyModel>()
        {
            new FamilyModel(1,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(2,"Aayush Pandit","Male",22,Relation.Father),
            new FamilyModel(3,"Aayush Pandit","Male",22,Relation.Father)

        };
        // ViewData["test"]="Testing right now!!!"; //j rakhna ni milcha dict ma, dictionary ho, default chai string linxa
        return View(list);
    }
}

MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc_web_app.Models;

namespace mvc_web_app.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Hello()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/Views/Hello/AddData.cshtml
@{
    ViewData["Title"] = "Add Data";
}

@using WebApplicationGui.Classes;

<form method="Post" enctype="multipart/form-data" asp-controller="Hello" asp-action="GetData">
    <table>
        @* <tr>
            <td>ID</td>
            <td><input type="number" id="numid" name="numid"></td>
            </tr> *@
        <tr>
            <td>Full Name</td>
            <td><input type="text" id="txtFullName" name="txtFullName"></td>

        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select name="txtGender" id="txtGender" runat="server">
                    <option value="Male" selected="selected">Male</option>
                    <option value="Female">Female</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Age:</td>
            <td><input type="number" id="numAge" name="numAge"></td>
        </tr>

        <tr>
            <td>Relation:</td>
            <td>
                <select name="txtRelation" id="txtRelation" runat="server">
                    <option value="0">Mother </option>
                    <option value="1">Father</option>
                    <option value="2">Brother</option>
                    <option value="3">Sister</option>
                    <option value="4">none</option>
                </select>
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"></td>
        </tr>
    </table>

</form>

@model List<FamilyModel>
<table class="table">
    <thead class="thead-dark table-bordered">
        <tr>
            <th>SN</th>
            <th>Full Name</th>
            <th>Gender</th>
            <th>Age</th>
            <th>Relation</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var f in Model)
        {
            <tr>
                <td>@f.id</td>
                <td>@f.fullName</td>
                <td>@f.gender</td>
                <td>@f.Age</td>
                <td>@f.relation</td>
            </tr>
        }
    </tbody>
</table>

MVC/Views/Hello/GetData.cshtml
@{
    ViewData["Title"]="Data";
}

@* @ViewData["data"]; *@
@using WebApplicationGui.Classes;

@ViewData["test"]

@model List<FamilyModel>
    <table class="table">
        <thead class="thead-dark table-bordered">
            <tr>
                <th>SN</th>
                <th>Full Name</th>
                <th>Gender</th>
                <th>Age</th>
                <th>Relation</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var f in Model)
        {
            <tr>
                <td>@f.id</td>
                <td>@f.fullName</td>
                <td>@f.gender</td>
                <td>@f.Age</td>
                <td>@f.relation</td>
            </tr>
        }
    </tbody>
    </table>

    

MVC/Views/Hello/index.cshtml
<h3>Hello</h3>

MVC/Views/Hello/searchData.cshtml
@using WebApplicationGui.Classes;
@model List<FamilyModel>
    <table class="table">
        <thead class="thead-dark table-bordered">
            <tr>
                <th>SN</th>
                <th>Full Name</th>
                <th>Gender</th>
                <th>Age</th>
                <th>Relation</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var f in Model)
        {
            <tr>
                <td>@f.id</td>
                <td>@f.fullName</td>
                <td>@f.gender</td>
                <td>@f.Age</td>
                <td>@f.relation</td>
            </tr>
        }
    </tbody>
    </table>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_web_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc_web_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_web_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="index">Hello</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="AddData">AddData</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="searchData">SearchData</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - mvc_web_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>